Lwasampijja baker
filetrust/k8-data-visualization pull request #4
Opened 2020-08-24 18:06 UTC by baker371

2020-08-24 21:14 UTC, dinis-cruz-gw requested changes
Hi, please see comments below, and you have a conflict to solve

2020-08-24 21:14 UTC, dinis-cruz-gw commented on requirements.txt
> +seaborn
Do we need this here?

I’m running the notebooks from inside docker

2020-08-24 21:14 UTC, dinis-cruz-gw commented on upwork-devs/lwasampijja-baker/Introduction_to_Google_Colab.ipynb
> +  "nbformat": 4,
This is a great notebook, really happy with it 👍 

One request , to review it I have to find it on your repo ( I.e. here https://github.com/baker371/k8-data-visualization/blob/lwasampijja-baker/upwork-devs/lwasampijja-baker/Introduction_to_Google_Colab.ipynb ), since that is where it is rendered.

For the next review of similar files, can you add the link to the Notebook to review to the PR text?

Thanks

2020-08-24 21:14 UTC, dinis-cruz-gw commented on upwork-devs/lwasampijja-baker/Introduction_to_Google_Colab.ipynb
> +  "nbformat": 4,
Or the link to the Slack screenshot?

2020-08-24 21:14 UTC, dinis-cruz-gw commented on upwork-devs/moses-mugo/models/issues.py
> +import pandas as pd
Question, why are you adding files to Moses folder?

Just curious and making sure it is not a mistake

2020-08-25 05:21 UTC, baker371 commented on requirements.txt
> +seaborn
This is not my work

2020-08-25 05:22 UTC, baker371 commented on upwork-devs/moses-mugo/models/issues.py
> +import pandas as pd
This is a mistake, not sure how I got mixed up with Moses's folder

2020-08-25 05:32 UTC, baker371 commented on requirements.txt
> +seaborn
Conflict resolved.

2020-08-26 23:48 UTC, merged